"""Schemas shared by the agentic planning workflow."""

from pydantic import BaseModel, Field

from ml_knowledge_hub.query.planner_schema import (
    PlannedAssetType,
    PlannedEntityType,
    PlannedOperation,
    PlannedQueryType,
)


class PlanEvaluation(BaseModel):
    """
    Structured critique generated by the Evaluator Agent.

    The evaluator critiques the planner's proposed plan.
    It does not answer the user's question.
    """

    # Whether the proposed plan is already suitable.
    valid: bool

    # Short explanation of the evaluator's reasoning.
    feedback: str

    # Specific problems identified in the plan.
    issues: list[str] = Field(
        default_factory=list
    )

    # --------------------------------------------------
    # Optional suggestions for the Planner Agent.
    #
    # The evaluator does NOT directly rewrite the plan.
    # These fields provide structured feedback that the
    # planner may consider during revision.
    # --------------------------------------------------
    suggested_query_type: PlannedQueryType | None = None

    suggested_operation: PlannedOperation | None = None

    suggested_entity_type: PlannedEntityType | None = None

    suggested_target_entity_type: PlannedEntityType | None = None

    suggested_asset_types: list[PlannedAssetType] | None = None